### ISSUE TITLE
Cannot create image

### ISSUE THREAD

**Issue by luqrei82** [UCSC-nanopore-cgl/MarginPolish#15]
Hello,

I'm trying to run HELEN after constructing images with MarginPolish.
This is a consensus of an HIV-1 amplicon with length around 1.7 kB assembled with Canu.

These are the commands up to HELEN:

![image](https://user-images.githubusercontent.com/59989712/113664322-84d30b00-96e6-11eb-8305-e1d9f3e16da4.png)

However, HELEN gave this output:

INFO: POLISH MODULE SELECTED
INFO: RUN-ID: 04062021_144058
INFO: PREDICTION OUTPUT DIRECTORY: /yshare2/ZETTAI_path_WA_slash_home_KARA/home/luqrei/work/niid/nishizawa/HIV-1_clones_seq/fastq_pass/deconvolution/bc01-16_canu_corrected_chopped_l1600_ml2000/48k_reads/kmer_binning_k6_n100_d0.5_s50_xi0.05_c0.04_fasta_non_chopped/bins/0/assembly_with_canu_2.1/marginPolish_plus_helen/helen/predictions_04062021_144058
INFO: CALL CONSENSUS STARTING
INFO: OUTPUT FILE: /yshare2/ZETTAI_path_WA_slash_home_KARA/home/luqrei/work/niid/nishizawa/HIV-1_clones_seq/fastq_pass/deconvolution/bc01-16_canu_corrected_chopped_l1600_ml2000/48k_reads/kmer_binning_k6_n100_d0.5_s50_xi0.05_c0.04_fasta_non_chopped/bins/0/assembly_with_canu_2.1/marginPolish_plus_helen/helen/predictions_04062021_144058/consensus_mP_plus_helen
Traceback (most recent call last):
  File "/home/luqrei/.local/bin/helen", line 8, in <module>
    sys.exit(main())
  File "/home/luqrei/.local/lib/python3.6/site-packages/helen/helen.py", line 313, in main
    FLAGS.callers)
  File "/home/luqrei/.local/lib/python3.6/site-packages/helen/modules/python/PolishInterface.py", line 87, in polish_genome
    callers)
  File "/home/luqrei/.local/lib/python3.6/site-packages/helen/modules/python/CallConsensusInterface.py", line 153, in call_consensus
    callers, threads_per_caller, num_workers)
  File "/home/luqrei/.local/lib/python3.6/site-packages/helen/modules/python/models/predict_cpu.py", line 217, in predict_cpu
    num_rle_classes=ImageSizeOptions.TOTAL_RLE_LABELS)
  File "/home/luqrei/.local/lib/python3.6/site-packages/helen/modules/python/models/ModelHander.py", line 50, in load_simple_model
    checkpoint = torch.load(model_path, map_location='cpu')
  File "/home/luqrei/.local/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/luqrei/.local/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.

When I tried to check the images created by MarginPolish using HDF viewer, it seems they do not contain any parameters, thus HELEN seems to fail loading the images due to empty files.

Is there any specific reason as to why MarginPolish cannot create images? Short amplicon sequence? No virus models? Wrong model chosen? Etc?

Thank you.

**Comment by tpesout** [comment]
Hi luqrei, sorry about taking so long to get back to you.  Can you try running the margin command on its own, and add the parameter `-a info` (to turn on debugging logging) and save the output to a text file: `./margin ... -a info 2>&1 | tee margin.log`.  If you look through there you might see the cause of the issue, and if not you can send it to me and I'll take a look.
